apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: trace-export-service
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/container-dependencies: "{app:[collector]}"
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/go-cloud-func-443003/cloud-run-source-deploy/trace-export-app
        name: app
        ports:
        - containerPort: 8080
        env:
        - name: "OTEL_EXPORTER_OTLP_ENDPOINT"
          value: "localhost:4317"
      - image: us-central1-docker.pkg.dev/go-cloud-func-443003/cloud-run-source-deploy/trace-export-collector
        name: collector
        startupProbe:
          httpGet:
            path: /
            port: 13133
        env: 
          - name: HONEYCOMB_API_KEY
            valueFrom:
              secretKeyRef:
                key: latest
                name: honeycomb-api-key