name: Example Workflow
on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    - name: setup-hi
      run: sleep 10
    - name: say-hi
      run: sleep 5 && echo "Hello!"
    - name: teardown-hi
      run: sleep 10